### ISSUE TITLE
Function sequence error with pypyodbc and MSSQL driver

### ISSUE THREAD

**Issue by zmlpjuran** [franz-see/Robotframework-Database-Library#49]
Hi, 
It happen randomly that when I call:
DatabaseLibrary.Execute Sql String delete t_Skill_Group_Member where AgentSkillTargetID = ${agent_id}, where ${agent_id} is a number

I get:
(u'HY010', u'[HY010] [unixODBC][Driver Manager]Function sequence error')

Traceback:
Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/DatabaseLibrary/query.py", line 252, in execute_sql_string self.__execute_sql(cur, sqlString) File "/usr/lib/python2.7/site-packages/DatabaseLibrary/query.py", line 260, in __execute_sql return cur.execute(sqlStatement) File "/usr/lib/python2.7/site-packages/pypyodbc.py", line 1605, in execute self.execdirect(query_string) File "/usr/lib/python2.7/site-packages/pypyodbc.py", line 1632, in execdirect self._NumOfRows() File "/usr/lib/python2.7/site-packages/pypyodbc.py", line 1796, in _NumOfRows check_success(self, ret) File "/usr/lib/python2.7/site-packages/pypyodbc.py", line 986, in check_success ctrl_err(SQL_HANDLE_STMT, ODBC_obj.stmt_h, ret, ODBC_obj.ansi) File "/usr/lib/python2.7/site-packages/pypyodbc.py", line 964, in ctrl_err raise Error(state,err_text)

My setup is following:
robotframework-databaselibrary (0.6)
pypyodbc (1.3.3)
and odbc driver 11 for SQL Server 2011.110.2270.00

I have read some article and it says that fetchall() prior getting num of rows can help. (we were solving similar issue here)
What I don't know is whether it should be fixed in database-library or in pypyodbc project.

**Comment by jerry57** [comment]
Please retest this with the code from master (not pypi).  I believe this is resolved.  If not, please feel free to submit a pull request with the changes and I will get it reviewed and merged as quickly as possible.

**Comment by jerry57** [comment]
Closing, nothing further heard on this and I believe it is resolved.
